#+TITLE: Better History

* Build

Il reste des choses a faire mais ca marche globalement.
- =npm run build/watch= fonctionne pas, j'ai du faire =node .\node_modules\webpack\bin\webpack.js --watch= pour que ca marche.
- =web-ext= se ferme pas correctement chez moi depuis powershell.
- Le fichier =.scss= n'est pas copie dans build.
- =npm run ext-reload-dev= est cense etre =web-ext run -s .\extension -f "C:\Program Files\Firefox Developer Edition\firefox.exe"=, parce que sinon sous Windows il va chercher dans C:\Program Files(x86)\Mozilla Firefox.

* Vues
** Day view

Liste des pages visitées dans la journée.

** Week view

7 colonnes par jour.
Chaque colonne contient la liste des pages visitées durant le jour.

** Month view

Vue calendrier.
Chaque "bloc" contient la liste de pages visitées durant le jour.

* Liens utiles

Web extension History API: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/history

Web extension Extension Page API: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/user_interface/Extension_pages

Design: https://design.firefox.com/photon/
